name: Update Errors specification
on:
  repository_dispatch:
    types: error-spec-change

jobs:
  snapshotErrorFile:
    env:
      CLIENT_ID: ${{ github.event.client_payload.id }}
      DOWNLOAD_URL: ${{ github.event.client_payload.download_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch OpenAPI doc
        run: ./scripts/fetch_api.sh ${{ env.DOWNLOAD_URL }}
      - uses: peter-evans/create-pull-request@v3
        with:
          title: "fix(errors): ${{ env.CLIENT_ID }} errors update"
          token: "${{ secrets.CI_USER_TOKEN }}"
          commit-message: >
              fix(errors): ${{ env.CLIENT_ID }} errors update
          author: "app-services-ci <app-services-ci@users.noreply.github.com>"
          branch: errors/update-${{ env.CLIENT_ID }}
          branch-suffix: timestamp
          reviewers: craicoverflow, wtrocki
          delete-branch: true
          body: >
            _This pull request was auto-generated_

            This PR adds latest version of the error specification for **${{ env.CLIENT_ID }}**.

            ## Actions:

                1. Review changes on the file. 
                2. If file adds, modifies or removes any error flags please approve this PR.
                3. Wait at least 20 minutes after creation and merge PR.
                4. Follow up PR with errors SDK will be created as result